//
// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.
//


class Solution {
public:
    char findTheDifference(string s, string t) {
        int sum_s = 0;
        int sum_t = 0;
        int len_s = s.size();
        for (int i = 0; i < len_s; i++) {
            sum_s += static_cast<int>(s.at(i));
            sum_t += static_cast<int>(t.at(i));
        }
        sum_t += static_cast<int>(t.at(len_s));
        return static_cast<char>(sum_t - sum_s);
    }
};
